### ISSUE TITLE
Internal Server Error when running on image of Not Art

### ISSUE THREAD

**Issue by kiphenglim** [qjulia32/art-team2-121#6]
This might totally be something you're aware of, but I tried to upload a random screenshot that I had on hand (i.e. not art) and it resulted in an internal server error. Ironically, the image was a screenshot of an internal server error inside our own app.

![Screenshot_2020-11-10 500 Internal Server Error](https://user-images.githubusercontent.com/45025466/98747073-a0223000-236b-11eb-8cf7-38782f31c2e3.jpg)

**Comment by cathrn3** [comment]
This is due to the file extension being a .png; for some reason .png uploads don't work on some computers but do work on others. We've removed .png as a valid extension for now so an appropriate error will show while we fix the bug.
